Add ability to update the array certificate + private key
Pure-Storage-Ansible/FlashBlade-Collection pull request #114
Opened 2020-12-11 12:10 UTC by jake2184

##### SUMMARY
Extend purefb_certs to allow updating the global array certificate

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
purefb_certs

##### ADDITIONAL INFORMATION

```paste below
- name: Set HTTPS certificate
  purestorage.flashblade.purefb_certs:
    name: global
    contents: "{{ lookup('file', 'mycertificate') }}"
    private_key: "{{ lookup('file', 'mycertificate.key') }}"
    passphrase: 'mypassword'
```

Tested on Pure 3.0.9

2020-12-11 14:38 UTC, sdodsley requested changes
This looks good, but before I fully review this can you ensure that `check_mode` works correctly for updates 
Can you also add an example of how to use these new parameters in the `Examples` section of the documentation

2020-12-11 17:31 UTC, jake2184 commented
Done

2020-12-14 07:33 UTC, dnix101 approved these changes
shipit

2020-12-14 13:53 UTC, sdodsley approved these changes

2020-12-14 13:53 UTC, merged