Add module to set global admin values
Pure-Storage-Ansible/FlashBlade-Collection pull request #164
Opened 2021-11-03 19:59 UTC by sdodsley

##### SUMMARY
New module to set max_logins, lockout_duration and min password length globally

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
purefb_admin.py

2021-12-14 16:43 UTC, rdeenik requested changes
Is there a way to remove these settings as well? The GUI does allows you to unset.

2021-12-14 16:43 UTC, rdeenik commented on collections/ansible_collections/purestorage/flashblade/changelogs/fragments/164_add_admin.yaml
> +  - purefa_admin - New module to manage global admin settings
Should be `purefb_admin`

2021-12-14 16:43 UTC, rdeenik commented on collections/ansible_collections/purestorage/flashblade/changelogs/fragments/176_nfs_export_policies.yaml
> + - purefb_info - Add NFS export policies and rules
Not sure if these changes are related to this PR?

2021-12-14 17:04 UTC, sdodsley commented
> Is there a way to remove these settings as well? The GUI does allows you to unset.

Setting the values to zero will remove them

2021-12-15 20:21 UTC, rdeenik approved these changes
Let's ship this. Quick note the values cannot be removed, as 0 is not an accepted value, but this seems related to the API.

2021-12-15 20:29 UTC, merged